### ISSUE TITLE
Confusion on Usage

### ISSUE THREAD

**Issue by rickwaugh1** [lazywithclass/winston-cloudwatch#3]
Can't get this to work, and it's difficult for me to tell how much more I have to do besides the example you have given.

I have an aws user with power user access. I created a short node script on an ec2 instance, which I have pasted below my question here. Winston works, I get both the "winston.error" line, and the "mainLog.log" line at the end both send messages to the console, and the last one also sends it's data to my log file. But nothing shows up in CloudWatch logs. I'm in us-west-2, and that is the region that is specified in the config file.

No errors, no nothing, just no logs. I was hoping, after looking at the someway nasty config files I'd need to muck with from Amazon, that someone had created this module, and figured it all out. ;)

So, have I missed some steps, or should this work?

aws_config = require("./aws_config.json");

var winston = require("winston"),
options = {
    logGroupName: 'test-log-group',
    logStreamName: 'test-log-stream'
  };
winston.add(require('winston-cloudwatch'), options);
winston.error('log this', { and: 'this too' });

//configure the main loggers. Sends to both the console the log file.
mainLog = new (winston.Logger)({
        transports: [
                new (winston.transports.Console)({ level: "info" }),
                new (winston.transports.File)({
                        filename: "./main.log",
                        level: "info",
                        json: false,
                        handleExceptions: true,
                        maxsize: 10000000000
                })
        ]
});

mainLog.log('info','test - again');

**Comment by rickwaugh1** [comment]
Added an ~/.aws/credentials file. Still no love.

**Comment by lazywithclass** [comment]
Sorry for asnwering so late.

I am working on it. I've updated the README with a notice about this.

**Comment by lazywithclass** [comment]
@rickwaugh1 I've made an update, you could find it in version `0.2.1`.
It's just a `setInterval` around the uploading function. I know it's not ideal, I will check it in the upcoming days on a system I own.

**Comment by rickwaugh1** [comment]
Thanks, hopefully I can try this out this week, too.

**Comment by rickwaugh1** [comment]
Hmm, still having issues. I get an error, saying I don't have a region. I looked in the code, and it looks like it's expecting awsRegion to be passed in the options, so I added this, as 'us-west-2', and I still got the error.

[ConfigError: Missing region in config]
  message: 'Missing region in config',
  code: 'ConfigError',
  time: Thu Feb 12 2015 10:26:04 GMT-0800 (PST) } 'ConfigError: Missing region in config\n    at Request.VALIDATE_REGION (/Users/rickwaugh/Documents/svn/Signul/ifttt-server/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/event_listeners.js:81:45)\n    at Request.callListeners (/Users/rickwaugh/Documents/svn/Signul/ifttt-server/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js:100:18)\n

var winston = require('winston');

var cloudWatchOptions =
{
    logGroupName: 'signul_dev',
    logStreamName: 'signul_dev',
    awsAccessKeyId: aws_config.accessKeyId,
    awsSecretKey: aws_config.secretAccessKey,
   awsRegion: aws_config.region
 };

winston.add(require('winston-cloudwatch'), cloudWatchOptions);

My options file, as it's passed in. I have xxed out my key and secret, of course.

{
    logGroupName: 'signul_dev',
    logStreamName: 'signul_dev',
    awsAccessKeyId: 'xxxx',
    awsSecretKey: 'xxx',
    region: 'us-west-2'
}

**Comment by lazywithclass** [comment]
I will check this in the next couple of hours on a new project with a fresh new server. I can't reproduce your error as of now.

Make sure you're using version `0.2.4` of this plugin.

**Comment by lazywithclass** [comment]
@rickwaugh1 please check `0.2.5`. Works on a new docker image without any previous environment setup.

**Comment by rickwaugh1** [comment]
Okay, did that, and it now accepts the region in the options file. But now I get an error about the log group not existing:

ResourceNotFoundException: The specified log group does not exist.

I'm trying to figure out how to create a log group, if I need one and no where that I can find in the AWS docs does it say how to do that. Is it the intention that I can simply run this module, specify a brand new log and stream name, and have those be created? That's how I thought it would work, but I could of course be mistaken.

**Comment by rickwaugh1** [comment]
Okay, I got this to go. Using the AWS CLI, I created a log group and a log stream. It then ran successfully. Yahoo. This can replace a whole set of servers and an sqs queue.

**Comment by lazywithclass** [comment]
I usually create log groups and log streams from [the web interface](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:).

I'm glad we got this working. I probably will deploy it on our infrastructure this week, so I will be able to see if anything goes wrong.

Thanks for the help ^^
