### ISSUE TITLE
InvalidParameterException: 1 validation error detected: Value '[]'

### ISSUE THREAD

**Issue by RameshJhajharia** [lazywithclass/winston-cloudwatch#55]
Hi Guys,

I saw that an issue was created for the same and was closed. Today I had pulled latest code and ran a test. I am still getting the same exception.

Thanks

**Comment by lazywithclass** [comment]
Hi Ramesh, could you please post here a simplified version of your test? So that I can reproduce the problem?

**Comment by lazywithclass** [comment]
Hi @RameshJhajharia, could you please post here a simplified version of your test? So that I can reproduce the problem?

**Comment by RameshJhajharia** [comment]
Hi @lazywithclass, So today I download the project from github, created aws config and tried running samples you have created in the example folder. When I went and checked in cloudwatch I can see that logs were created but after creating logs I started getting following exception:

{ [InvalidParameterException: 1 validation error detected: Value '[]' at 'logEvents' failed to satisfy constraint: Member must have length greater than or equal to 1]
  message: '1 validation error detected: Value \'[]\' at \'logEvents\' failed to satisfy constraint: Member must have length greater than or equal to 1',
  code: 'InvalidParameterException',
  time: Tue Dec 06 2016 17:44:04 GMT+0530 (IST),
  requestId: '7a7bd1fd-bbad-11e6-98cc-71df9763104d',
  statusCode: 400,
  retryable: false,
  retryDelay: 99.50839537195861 }

**Comment by lazywithclass** [comment]
Ok thanks, I will run those too and check what's wrong.

**Comment by lazywithclass** [comment]
@RameshJhajharia Hello, I think I need more info from you, which one is the example you are having problems with? I've just run `node examples/simple.js` with my AWS credentials and it works fine.

I might have an idea of what's causing this but it would be much easier with the exact code you're using.

**Comment by RameshJhajharia** [comment]
@lazywithclass I had tried running `simple.js, multiple-loggers.js,simple-with-aws-options.js`. I was getting exception for all of these.

It is creating log in cloud and I think after that it is still trying to upload more logs.

Here is the complete consolle log of `simple.js`:
`{ logGroupName: 'testing', logStreamName: 'first' }
error: 1
{ [InvalidParameterException: 1 validation error detected: Value '[]' at 'logEvents' failed to satisfy constraint: Member must have length greater than or equal to 1]
  message: '1 validation error detected: Value \'[]\' at \'logEvents\' failed to satisfy constraint: Member must have length greater than or equal to 1',
  code: 'InvalidParameterException',
  time: Tue Dec 06 2016 19:49:40 GMT+0530 (IST),
  requestId: '069aba82-bbbf-11e6-8c95-87696aad8727',
  statusCode: 400,
  retryable: false,
  retryDelay: 19.625550624914467 }
`

**Comment by lazywithclass** [comment]
It's running in a `setInterval` loop, but it shouldn't try to upload more logs if there's none, I am investigating right now.

**Comment by lazywithclass** [comment]
Ok @RameshJhajharia the problem does not happen in simple.js but it does happen in multiple-loggers.js, I'm adding the bug tag and working on it.

**Comment by lazywithclass** [comment]
@RameshJhajharia the problem does not seem to affect log upload, I am creating a sample app that I will run constantly to have a look at this in detail, and possibly to spot any other intermittent error.

Could you please confirm that your logs are always saved regardless of the error you receive in the console?

**Comment by Omnomios** [comment]
Hey @lazywithclass, I can confirm that the logs are being saved when the `InvalidParameterException` error is being thrown.

If there's any way I can help you debug this, let me know.

**Comment by lazywithclass** [comment]
Hi @Omnomios the problem is due to the fact that somehow an empty `logEvents` gets passed through, I am a bit confused about that, it should not happen, I suspect I'm missing some behaviour of shared state when `setInterval` is involved. I will get back to this. The fix is easy, understanding it is taking a bit more.

**Comment by groteworld** [comment]
Has there been any update on what is the cause of this or what is a work around in the meantime?  Thank you!

**Comment by lazywithclass** [comment]
Hey @groteworld I am sorry I never actually implemented the fix, meanwhile I got accepted at https://www.recurse.com/ and I'm currently half way through my batch. 

The upload feature is not affected by this bug, I know though that's annoying and alarming to see those errors. I will create some space to properly address this issue, I don't want to just slap in a dirty fix.

**Comment by lazywithclass** [comment]
Thanks for the patience, work is happening here: https://github.com/lazywithclass/winston-cloudwatch/tree/real-process-to-test-erroring-scenario

I am also considering to move away from `setInterval` it was a hacky way of reaching my goal when I first coded this but now is giving me more headaches than benefits. I am thinking about trying a backoff module, if anyone has suggestion feel free!

**Comment by lazywithclass** [comment]
@RameshJhajharia @Omnomios @groteworld I've just pushed v1.11.0 which should address the above problems and others.

To allow better debugging on both mine and your side, and to see the library in action if you're curious I've created a [simulation](https://github.com/lazywithclass/winston-cloudwatch#simulation), please take a look and it would be great if you could check that you don't see any more errors using it, because I don't on my side.

Thanks for reporting this issue and sorry again for the extremely delayed answer. Hope this helps.

**Comment by lazywithclass** [comment]
Let me know if this is any better, I can tweak it if needed, otherwise I will close this.

Thanks!

**Comment by Omnomios** [comment]
My apologies. Didn't meant to leave you hanging. I'll update the package on my end and test it for a few days and let you know how it goes. 

Thanks for the great work, if this sorts it out I'll be very happy.

**Comment by lazywithclass** [comment]
@Omnomios no worries, anyway we are in a better position now: problems and edge case scenarios can now be tested using [the simulation](https://github.com/lazywithclass/winston-cloudwatch#simulation), so even if the problem is still there we have the tools to track it down.

**Comment by alecl** [comment]
I still see this error on every run of my code using 1.11.1.

**Comment by lazywithclass** [comment]
@alecl do you see that when running the simulation?
Could you please post a runnable snippet of your scenario so I can replicate it?

**Comment by TimJohns** [comment]
I owe you all an apology - I fixed this in my branch quite a while back and didn't submit a PR. This week, we were reworking some of our logging and got off of our fork and so grabbed the latest NPM module, and noticed this came back -- so I came here and noticed this thread.

The code has diverged significantly, so my fix at https://github.com/TillerHQ/winston-cloudwatch/commit/d0a2d56449308b54a8195e413ba7f80dfc96cc46 won't work anymore -- but I will see if I can port the fix in the latest codebase and submit a PR.

The gist of the problem is described in the comments in cloudwatch-integration.js at the commit listed above. Essentially, upload() can be called at a greater rate than getToken(), which overlaps calls to getToken(). Once the first getToken() returns,  the logEvents.splice() empties the array, and when the second call to getToken() returns, if no other calls to upload() have occurred in the interim, so the array it submits is still empty - resulting in the InvalidParameterException returned by AWS.

You guys fixed the (unrelated) token sequence exception differently than I did, so the fix in my fork won't work as-is. By quick inspection it looks like the fix for the HEAD of master in the main fork is to move the setting of lib._postingEvents to before the call to getToken(), [and make sure it gets cleared before calling cb() in all of the error cases]. 

I'll see if I can get that done and tested and see if I can get a PR in tonight -- really sorry about that!

- Tim

**Comment by lazywithclass** [comment]
@TimJohns No apologies needed, thanks for your help, you just have explained one thing that kept on bothering me for ages! :D

I have gone through your PR over the weekend but couldn't really understand the best way to integrate it, I also want to cover it with tests, so I am getting coverage back to 100%, then I will port it, with tests.

I am worried that we might lose some functionality, this is why it's taking me so much time.

**Comment by TimJohns** [comment]
Sounds good, let me know if you need some help; I can make the change easily to a different commit on a different branch if that would help.  Also it just _looks_ crazy because I indented to move most of the code to a nested function, so diff thinks I changed a whole bunch of lines.  

This diff that ignores whitespace is MUCH cleaner:

git diff -w c4ce08919499a2b3d48608e966098128661e9d84 .

Coverage should have increased slightly due to the nature of the change, but I'll add a test or two to the PR branch that also illustrates the problem and validates the fix.

**Comment by alecl** [comment]
You can also add ?w=1 to the github diff web pages to ignore the whitespace there too in case that's helpful.

**Comment by lazywithclass** [comment]
@TimJohns yes, tests would help me write less code, I'm getting the projet back to 100% right now.

I've removed whitespace from your PR, lol, now I see what you meant! Have a look at it: https://github.com/lazywithclass/winston-cloudwatch/pull/61/commits/c086568a08a141d03af702e4c735c343d3ff2467?w=true, now I get it!

**Comment by lazywithclass** [comment]
@TimJohns it turned out to be easier to copy paste code than to resolve the conflict I had, I made sure to include you as the much appreciated author of it, thanks again.

I will now test this and proceed to release 1.11.3, which will contain the fix.

**Comment by lazywithclass** [comment]
1.11.3 is out. Please let me know if it fixes the problem, so we can close this.

**Comment by lazywithclass** [comment]
I am considering this as closed, let me know if it's resolved.

@RameshJhajharia @TimJohns @alecl @Omnomios @groteworld
